// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfBrocmAzh85Nltnr2bcSyZX3y6WNCmgE',
    appId: '1:534696389789:web:2344d5ea43441da4663874',
    messagingSenderId: '534696389789',
    projectId: 'test-479c3',
    authDomain: 'test-479c3.firebaseapp.com',
    storageBucket: 'test-479c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH3gFE9Yknr31H5m6bWYCYAjzJ5ziKYak',
    appId: '1:534696389789:android:cea5cadef9a32735663874',
    messagingSenderId: '534696389789',
    projectId: 'test-479c3',
    storageBucket: 'test-479c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZy_yEUs14EXbc-jjhFcasllhEz3XZXFQ',
    appId: '1:534696389789:ios:e9f77c2c5e83dc50663874',
    messagingSenderId: '534696389789',
    projectId: 'test-479c3',
    storageBucket: 'test-479c3.appspot.com',
    androidClientId: '534696389789-6bh0d60fv6kfgimoqipg82632r74h59b.apps.googleusercontent.com',
    iosClientId: '534696389789-3njof3ano53dpfr1ijcclpr8t8caqu73.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseStorageFp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZy_yEUs14EXbc-jjhFcasllhEz3XZXFQ',
    appId: '1:534696389789:ios:e9f77c2c5e83dc50663874',
    messagingSenderId: '534696389789',
    projectId: 'test-479c3',
    storageBucket: 'test-479c3.appspot.com',
    androidClientId: '534696389789-6bh0d60fv6kfgimoqipg82632r74h59b.apps.googleusercontent.com',
    iosClientId: '534696389789-3njof3ano53dpfr1ijcclpr8t8caqu73.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseStorageFp',
  );
}
